Use math.gcd
fractions.gcd is deprecated from Python 3.5 and it's been removed in Python 3.9, so using fractions.gcd
the activity fails to start with "ImportError: cannot import name 'gcd' from 'fractions'" on F33 SoaS as it uses Python 3.9

Signed-off-by: Ibiam Chihurumnaya <ibiamchihurumnaya@gmail.com>